version: '3'

services:
  mysql-main:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wallet_main
    volumes:
      - mysql-db-main:/bitnami/mysql/data
    ports:
      - "3306:3306"
  
  app:
    restart: always
    build: .
    ports:
      - 8000:8000
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_TRACK_MODIFICATIONS=True
      - JSON_SORT_KEYS=JSON_SORT_KEYS=True
      - JWT_SECRET_KEY=dsakljes#@154nmvfg
      - DATABASE_HOST=mysql-main
      - DATABASE_NAME=wallet_main
      - DATABASE_PASSWORD=1234
      - DATABASE_USER=root
    volumes:
      - .:/app
    depends_on:
      - "mysql-main"

volumes:
  mysql-db-main: