"""adding relationship between tables

Revision ID: a58005f47777
Revises: bc5afe2e2853
Create Date: 2021-12-29 09:00:26.272531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58005f47777'
down_revision = 'bc5afe2e2853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders_products', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders_products', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
